import type { PageContentField } from "@/types";

export const expertiseFields: PageContentField[] = [
  { key: "hero.badge", label: "Hero - badge", type: "text" },
  { key: "hero.heading", label: "Hero - titre", type: "text" },
  { key: "hero.description", label: "Hero - description", type: "textarea" },
  { key: "hero.subheading.part1", label: "Hero - sous-titre partie 1", type: "text" },
  { key: "hero.subheading.part2", label: "Hero - sous-titre partie 2", type: "text" },
  { key: "hero.subheading.part3", label: "Hero - sous-titre partie 3", type: "text" },
  { key: "hero.cta1", label: "Hero - bouton 1", type: "text" },
  { key: "hero.cta2", label: "Hero - bouton 2", type: "text" },
  { key: "certificate.badge", label: "Certificat - badge", type: "text" },
  { key: "certificate.heading", label: "Certificat - titre", type: "text" },
  { key: "certificate.description", label: "Certificat - description", type: "textarea" },
  { key: "certificate.differenceHeading", label: "Certificat - titre différence", type: "text" },
  { key: "certificate.differenceDescription", label: "Certificat - description différence", type: "textarea" },
  { key: "certificate.cta1", label: "Certificat - bouton 1", type: "text" },
  { key: "certificate.cta2", label: "Certificat - bouton 2", type: "text" },
  { key: "comparison.badge", label: "Comparaison - badge", type: "text" },
  { key: "comparison.heading", label: "Comparaison - titre", type: "text" },
  { key: "comparison.headingTalents", label: "Comparaison - titre talents", type: "text" },
  { key: "comparison.columnTheme", label: "Comparaison - colonne thème", type: "text" },
  { key: "comparison.columnTalents", label: "Comparaison - colonne talents", type: "text" },
  { key: "comparison.columnVulnerables", label: "Comparaison - colonne vulnérables", type: "text" },
  { key: "comparison.gapBadge", label: "Comparaison - badge écart", type: "text" },
  { key: "comparison.gapHeading", label: "Comparaison - titre écart", type: "text" },
  { key: "comparison.gapHeadingHighlight", label: "Comparaison - titre écart accentué", type: "text" },
  { key: "omt.badge", label: "O-M-T - badge", type: "text" },
  { key: "omt.heading", label: "O-M-T - titre", type: "text" },
  { key: "omt.headingHighlight", label: "O-M-T - titre accentué", type: "text" },
  { key: "omt.description", label: "O-M-T - description", type: "textarea" },
  { key: "omt.cta", label: "O-M-T - bouton", type: "text" },
  { key: "services.badge", label: "Services - badge", type: "text" },
  { key: "services.heading", label: "Services - titre", type: "text" },
  { key: "services.description", label: "Services - description", type: "textarea" },
  { key: "services.learnMore", label: "Services - bouton en savoir plus", type: "text" },
  { key: "tertiles.badge", label: "Tertiles - badge", type: "text" },
  { key: "tertiles.heading", label: "Tertiles - titre", type: "text" },
  { key: "tertiles.headingHighlight", label: "Tertiles - titre accentué", type: "text" },
  { key: "tertiles.description", label: "Tertiles - description", type: "textarea" },
  { key: "tertiles.note", label: "Tertiles - note", type: "textarea" },
  { key: "vigiScore.badge", label: "Vigi-Score - badge", type: "text" },
  { key: "vigiScore.headingPrefix", label: "Vigi-Score - préfixe du titre", type: "text" },
  { key: "vigiScore.description", label: "Vigi-Score - description", type: "textarea" },
  { key: "vigiScore.assemblyHeading", label: "Vigi-Score - titre assemblage", type: "text" },
  { key: "vigiScore.assemblyHighlight", label: "Vigi-Score - accentuation assemblage", type: "text" },
  { key: "vigiScore.resultLabel", label: "Vigi-Score - libellé résultat", type: "text" },
  { key: "vigiScore.resultDescription", label: "Vigi-Score - description résultat", type: "textarea" },
  { key: "vigiScore.tendencyHeading", label: "Vigi-Score - titre tendance", type: "text" },
  { key: "vigiScore.tendencyDescription", label: "Vigi-Score - description tendance", type: "textarea" },
  { key: "vigilance.badge", label: "Vigilance - badge", type: "text" },
  { key: "vigilance.headingVulnerability", label: "Vigilance - titre vulnérabilité", type: "text" },
  { key: "vigilance.headingVigilance", label: "Vigilance - titre vigilance", type: "text" },
  { key: "vigilance.vulnerabilityTitle", label: "Vigilance - sous-titre vulnérabilité", type: "text" },
  { key: "vigilance.vulnerabilityDescription", label: "Vigilance - description vulnérabilité", type: "textarea" },
  { key: "vigilance.vigilanceTitle", label: "Vigilance - sous-titre vigilance", type: "text" },
  { key: "vigilance.vigilanceDescription", label: "Vigilance - description vigilance", type: "textarea" },
  { key: "vigilance.gaugeLow", label: "Vigilance - jauge basse", type: "text" },
  { key: "vigilance.gaugeVulnerability", label: "Vigilance - jauge vulnérabilité", type: "text" },
  { key: "vigilance.gaugeVigilance", label: "Vigilance - jauge vigilance", type: "text" },
  { key: "vigilance.gaugeHigh", label: "Vigilance - jauge haute", type: "text" },
  { key: "vigilance.ncHeading", label: "Vigilance - titre non-conformité", type: "text" },
  { key: "vigilance.ncHeadingHighlight", label: "Vigilance - titre non-conformité accentué", type: "text" },
  { key: "vigilance.ncDescription", label: "Vigilance - description non-conformité", type: "textarea" },
  { key: "cta.badge", label: "CTA - badge", type: "text" },
  { key: "cta.heading", label: "CTA - titre", type: "text" },
  { key: "cta.description", label: "CTA - description", type: "textarea" },
  { key: "cta.cta1", label: "CTA - bouton 1", type: "text" },
  { key: "cta.cta2", label: "CTA - bouton 2", type: "text" },
];
