import type { PageContentField } from "@/types";

export const homeFields: PageContentField[] = [
  { key: "hero.badge", label: "Hero - badge", type: "text" },
  { key: "hero.titleLine1", label: "Hero - titre ligne 1", type: "text" },
  { key: "hero.titleLine2", label: "Hero - titre ligne 2", type: "text" },
  { key: "hero.titleLine3", label: "Hero - titre ligne 3", type: "text" },
  { key: "hero.titleLine4", label: "Hero - titre ligne 4", type: "text" },
  { key: "hero.baseline", label: "Hero - accroche", type: "text" },
  { key: "hero.slogan", label: "Hero - slogan", type: "text" },
  { key: "hero.subtitle", label: "Hero - sous-titre", type: "textarea" },
  { key: "hero.discoverRating", label: "Hero - bouton découvrir la notation", type: "text" },
  { key: "hero.requestEvaluation", label: "Hero - bouton demander une évaluation", type: "text" },
  { key: "hero.trustIndicator", label: "Hero - texte de confiance", type: "text" },
  { key: "adn.badge", label: "ADN - badge", type: "text" },
  { key: "adn.heading", label: "ADN - titre", type: "text" },
  { key: "adn.description", label: "ADN - description", type: "textarea" },
  { key: "adn.assemblyLabel", label: "ADN - libellé assemblage", type: "text" },
  { key: "adn.understandRating", label: "ADN - bouton comprendre la notation", type: "text" },
  { key: "pillars.badge", label: "Piliers - badge", type: "text" },
  { key: "pillars.heading", label: "Piliers - titre", type: "text" },
  { key: "pillars.description", label: "Piliers - description", type: "textarea" },
  { key: "services.badge", label: "Services - badge", type: "text" },
  { key: "services.heading", label: "Services - titre", type: "text" },
  { key: "services.description", label: "Services - description", type: "textarea" },
  { key: "services.viewAll", label: "Services - bouton voir tout", type: "text" },
  { key: "organizations.badge", label: "Organisations - badge", type: "text" },
  { key: "organizations.heading", label: "Organisations - titre", type: "text" },
  { key: "organizations.description", label: "Organisations - description", type: "textarea" },
  { key: "testimonials.badge", label: "Témoignages - badge", type: "text" },
  { key: "testimonials.heading", label: "Témoignages - titre", type: "text" },
  { key: "testimonials.pullQuote", label: "Témoignage - citation", type: "textarea" },
  { key: "testimonials.paragraph1", label: "Témoignage - paragraphe 1", type: "textarea" },
  { key: "testimonials.paragraph2", label: "Témoignage - paragraphe 2", type: "textarea" },
  { key: "testimonials.paragraph3", label: "Témoignage - paragraphe 3", type: "textarea" },
  { key: "testimonials.paragraph4", label: "Témoignage - paragraphe 4", type: "textarea" },
  { key: "testimonials.authorName", label: "Témoignage - nom de l'auteur", type: "text" },
  { key: "testimonials.authorRole", label: "Témoignage - rôle de l'auteur", type: "text" },
  { key: "testimonials.authorCompany", label: "Témoignage - entreprise de l'auteur", type: "text" },
  { key: "cta.heading", label: "CTA final - titre", type: "text" },
  { key: "cta.description", label: "CTA final - description", type: "textarea" },
  { key: "cta.requestEvaluation", label: "CTA final - bouton demander une évaluation", type: "text" },
  { key: "cta.clientArea", label: "CTA final - bouton espace client", type: "text" },
];
