import type { PageContentField } from "@/types";

export const servicesFields: PageContentField[] = [
  { key: "hero.badge", label: "Hero - badge", type: "text" },
  { key: "hero.heading", label: "Hero - titre", type: "text" },
  { key: "hero.description", label: "Hero - description", type: "textarea" },
  { key: "hero.subdescription", label: "Hero - sous-description", type: "textarea" },
  { key: "hero.discoverRating", label: "Hero - bouton découvrir la notation", type: "text" },
  { key: "hero.contactUs", label: "Hero - bouton contact", type: "text" },
  { key: "approach.badge", label: "Approche - badge", type: "text" },
  { key: "approach.heading", label: "Approche - titre", type: "text" },
  { key: "approach.watermark", label: "Approche - filigrane", type: "text" },
  { key: "approach.anchor1Title", label: "Approche - ancre 1 titre", type: "text" },
  { key: "approach.anchor1Subtitle", label: "Approche - ancre 1 sous-titre", type: "text" },
  { key: "approach.anchor1Desc", label: "Approche - ancre 1 description", type: "textarea" },
  { key: "approach.anchor2Title", label: "Approche - ancre 2 titre", type: "text" },
  { key: "approach.anchor2Subtitle", label: "Approche - ancre 2 sous-titre", type: "text" },
  { key: "approach.anchor2Desc", label: "Approche - ancre 2 description", type: "textarea" },
  { key: "approach.anchor3Title", label: "Approche - ancre 3 titre", type: "text" },
  { key: "approach.anchor3Subtitle", label: "Approche - ancre 3 sous-titre", type: "text" },
  { key: "approach.anchor3Desc", label: "Approche - ancre 3 description", type: "textarea" },
  { key: "approach.learnMore", label: "Approche - bouton en savoir plus", type: "text" },
  { key: "catalog.badge", label: "Catalogue - badge", type: "text" },
  { key: "catalog.heading", label: "Catalogue - titre", type: "text" },
  { key: "catalog.description", label: "Catalogue - description", type: "textarea" },
  { key: "pillars.heading", label: "Piliers - titre", type: "text" },
  { key: "pillars.description", label: "Piliers - description", type: "textarea" },
  { key: "process.heading", label: "Processus - titre", type: "text" },
  { key: "process.description", label: "Processus - description", type: "textarea" },
  { key: "cta.heading", label: "CTA - titre", type: "text" },
  { key: "cta.description", label: "CTA - description", type: "textarea" },
  { key: "cta.ourRating", label: "CTA - bouton notre notation", type: "text" },
  { key: "cta.requestEvaluation", label: "CTA - bouton demander une évaluation", type: "text" },
];
