-- ============================================================================
-- CETé — table services (catalogue Expertise/Conseil, ex-JSON statique)
-- ============================================================================

create table if not exists public.services (
  id                 text primary key,      -- identifiants stables (exp-dps, srv-campus...)
  category           text not null,         -- "Expertise" | "Conseil"
  type               text not null,         -- "expertise" | "service"
  is_pillar          boolean not null default false,
  title              jsonb not null,        -- {fr, en}
  description        jsonb not null,        -- {fr, en}
  short_description  jsonb not null,        -- {fr, en}
  features           jsonb not null default '{"fr":[],"en":[]}'::jsonb,  -- {fr:[], en:[]}
  icon               text not null,
  image_url          text not null default '',
  sort_order         int not null default 999,
  visible            boolean not null default true,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);
alter table public.services enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'services' and policyname = 'services_admin_all'
  ) then
    create policy "services_admin_all" on public.services
      for all using (public.is_admin()) with check (public.is_admin());
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'services' and policyname = 'services_public_select'
  ) then
    create policy "services_public_select" on public.services
      for select using (visible = true);
  end if;
end $$;

-- Seed depuis src/data/mocks/{fr,en}/services.json (idempotent via id fixe)
insert into public.services (id, category, type, is_pillar, title, description, short_description, features, icon, image_url, sort_order) values
  ('exp-dps', 'Expertise', 'expertise', true, '{"fr": "DPS - Diagnostic Performance Sécurité", "en": "DPS - Safety Performance Diagnosis"}'::jsonb, '{"fr": "Audit terrain et expertise de votre système de maîtrise du risque électrique. Le DPS est le socle de la démarche CETé : analyse, notation, certificat et accompagnement pour la prévention et la sécurité électrique.", "en": "Field audit and expert assessment of your electrical risk management system. The DPS is the cornerstone of the CETé approach: analysis, rating, certification, and ongoing support for electrical safety and prevention."}'::jsonb, '{"fr": "Audit du risque électrique sur le terrain - base de votre notation et certification", "en": "On-site electrical risk audit - the foundation of your rating and certification"}'::jsonb, '{"fr": ["Analyse de l''auto-évaluation du prescrit réglementaire", "Analyse de l''organisation et de la maîtrise opérationnelle sur chantier représentatif", "Rapport avec management visuel sur 4 niveaux de lecture", "Recommandations et notation en comité de suivi", "Remise d''un certificat pour valoir ce que de droit", "Accompagnement au plan d''actions de progrès", "Abonnement newsletter pendant la durée de certification"], "en": ["Analysis of regulatory compliance self-assessment", "Analysis of organization and operational control on a representative worksite", "Report with visual management across 4 reading levels", "Recommendations and rating issued by the monitoring committee", "Issuance of a certificate for all relevant purposes", "Support for the improvement action plan", "Newsletter subscription for the duration of certification"]}'::jsonb, 'clipboard-check', '', 1),
  ('exp-save', 'Expertise', 'expertise', true, '{"fr": "SAVE - Scan d''Analyse de Vulnérabilité des Événements", "en": "SAVE - Event Vulnerability Analysis Scan"}'::jsonb, '{"fr": "Expertise d''appui à l''analyse d''événements : accidents, chaudes alertes, presqu''accidents, situations dangereuses. Un regard indépendant pour comprendre et prévenir.", "en": "Expert support for event analysis: accidents, close calls, near-misses, and hazardous situations. An independent perspective to understand and prevent."}'::jsonb, '{"fr": "Analyse experte d''événements pour comprendre et prévenir", "en": "Expert event analysis to understand and prevent incidents"}'::jsonb, '{"fr": ["Analyse approfondie de l''événement", "Recommandations ciblées", "Rédaction d''un compte-rendu détaillé", "Accompagnement au plan d''actions de progrès"], "en": ["In-depth event analysis", "Targeted recommendations", "Detailed incident report preparation", "Support for the improvement action plan"]}'::jsonb, 'shield-alert', '/images/services/save.png', 2),
  ('srv-campus', 'Conseil', 'service', true, '{"fr": "Campus CPF - Coaching, Performance, Formation", "en": "Campus CPF - Coaching, Performance, Training"}'::jsonb, '{"fr": "Le triptyque gagnant de la Performance : conseils et accompagnement sur mesure pour faire progresser vos équipes et votre organisation.", "en": "The winning triptych of Performance: tailored advice and support to advance your teams and your organization."}'::jsonb, '{"fr": "Le triptyque gagnant : Coaching - Performance - Formation", "en": "The winning triptych: Coaching - Performance - Training"}'::jsonb, '{"fr": ["VIR-ELEX", "Coaching individuel ou collectif", "Professionnalisation et formation", "Coaching pour l''obtention d''une aptitude à un marché", "Coaching pour l''agrément d''un Organisme de formation"], "en": ["VIR-ELEX", "Individual or group coaching", "Professional development and training", "Coaching for market certification eligibility", "Coaching for training organization accreditation"]}'::jsonb, 'graduation-cap', '/images/services/campus-cpf.png', 3),
  ('srv-pass-vip', 'Conseil', 'service', true, '{"fr": "PASS-Sérénité VIP", "en": "PASS-Sérénité VIP"}'::jsonb, '{"fr": "Votre accès privilégié à l''écosystème CETé ADN : veille réglementaire, base de connaissances, outils partenaires et animation de vos référents.", "en": "Your privileged access to the CETé ADN ecosystem: regulatory monitoring, knowledge base, partner tools, and facilitation for your key contacts."}'::jsonb, '{"fr": "Accès privilégié à l''écosystème CETé ADN", "en": "Privileged access to the CETé ADN ecosystem"}'::jsonb, '{"fr": ["Accès à l''espace VIP de CETé ADN", "Abonnement à la newsletter", "Veille réglementaire CETé ADN", "Base Questions/Réponses CETé ADN", "Synthèse annuelle des DPS", "Animation des Encadrants et Formateurs Référents", "Les TST pour les nuls", "Éligibilité aux outils partenaires : Viz-Act, VISA, Vi.T.A.L, VESTA, VISU…"], "en": ["Access to the CETé ADN VIP portal", "Newsletter subscription", "CETé ADN regulatory monitoring", "CETé ADN Q&A knowledge base", "Annual DPS summary report", "Facilitation for supervisors and lead trainers", "Live-Line Work for beginners", "Eligibility for partner tools: Viz-Act, VISA, Vi.T.A.L, VESTA, VISU..."]}'::jsonb, 'crown', '/images/services/pass-serenite-vip.png', 4),
  ('exp-vigi', 'Expertise', 'expertise', false, '{"fr": "Vigi-Score - Notation Indépendante", "en": "Vigi-Score - Independent Rating"}'::jsonb, '{"fr": "Rating indépendant de votre maîtrise du risque électrique sur l''échelle AAA-DDD. Le produit central de CETé.", "en": "Independent rating of your electrical risk management on the AAA-DDD scale. The core product of CETé."}'::jsonb, '{"fr": "Votre notation officielle de AAA à DDD", "en": "Your official rating from AAA to DDD"}'::jsonb, '{"fr": ["Notation sur échelle AAA à DDD", "Rapport de notation détaillé par axe", "Benchmark sectoriel anonymisé", "Réévaluation annuelle ou trimestrielle"], "en": ["Rating on the AAA to DDD scale", "Detailed rating report by assessment axis", "Anonymized industry benchmark", "Annual or quarterly reassessment"]}'::jsonb, 'star', '', 5),
  ('srv-coach-mgr', 'Conseil', 'service', false, '{"fr": "Coaching Dirigeants & QSE", "en": "Executive & HSE Leadership Coaching"}'::jsonb, '{"fr": "Accompagnement des décideurs pour intégrer la maîtrise du risque électrique dans leur stratégie opérationnelle.", "en": "Supporting decision-makers in integrating electrical risk management into their operational strategy."}'::jsonb, '{"fr": "Pilotage stratégique du risque électrique", "en": "Strategic electrical risk management"}'::jsonb, '{"fr": ["Séminaire de direction : 1 à 2 jours", "Tableaux de bord KPI risque électrique", "Coaching individuel du responsable QSE", "Livrable : feuille de route vers le AAA"], "en": ["Executive seminar: 1 to 2 days", "Electrical risk KPI dashboards", "Individual coaching for HSE managers", "Deliverable: roadmap to AAA"]}'::jsonb, 'users', '', 6),
  ('srv-coach-tst', 'Conseil', 'service', false, '{"fr": "Coaching Animateurs TST", "en": "Live-Line Work Coordinator Coaching"}'::jsonb, '{"fr": "Formation avancée des animateurs Travaux Sous Tension pour renforcer la maîtrise opérationnelle terrain.", "en": "Advanced training for live-line work coordinators to strengthen operational field expertise."}'::jsonb, '{"fr": "Renforcement des compétences TST terrain", "en": "Strengthening live-line work field competencies"}'::jsonb, '{"fr": ["Modules avancés : 3 à 5 jours", "Mises en situation terrain supervisées", "Évaluation individuelle des compétences", "Livrable : plan de montée en compétence"], "en": ["Advanced modules: 3 to 5 days", "Supervised field exercises", "Individual competency assessment", "Deliverable: skills development plan"]}'::jsonb, 'zap', '', 7),
  ('srv-coach-encad', 'Conseil', 'service', false, '{"fr": "Coaching Encadrement Chantier", "en": "Site Supervision Coaching"}'::jsonb, '{"fr": "Formation des chefs de chantier et encadrants de proximité à la gestion quotidienne du risque électrique.", "en": "Training for site managers and frontline supervisors in day-to-day electrical risk management."}'::jsonb, '{"fr": "Maîtrise du risque au niveau opérationnel", "en": "Risk management at the operational level"}'::jsonb, '{"fr": ["Formation terrain : 2 à 3 jours par groupe", "Audit chantier avec restitution immédiate", "Mentoring individuel sur 3 mois", "Livrable : grille d''autocontrôle chantier"], "en": ["Field training: 2 to 3 days per group", "On-site audit with immediate debrief", "Individual mentoring over 3 months", "Deliverable: site self-assessment checklist"]}'::jsonb, 'hard-hat', '', 8),
  ('srv-form-orgs', 'Conseil', 'service', false, '{"fr": "Accompagnement Organismes de Formation", "en": "Training Organization Support"}'::jsonb, '{"fr": "Support méthodologique et contenus pour les organismes souhaitant intégrer le référentiel CETé dans leurs cursus.", "en": "Methodological support and content for training organizations seeking to integrate the CETé framework into their curricula."}'::jsonb, '{"fr": "Intégration du référentiel CETé dans vos formations", "en": "Integrating the CETé framework into your training programs"}'::jsonb, '{"fr": ["Audit pédagogique de vos contenus existants", "Contenus certifiés conformes au référentiel CETé", "Partenariat formalisé sur 12 mois", "Livrable : kit formateur et supports de cours"], "en": ["Pedagogical audit of your existing content", "Content certified compliant with the CETé framework", "Formalized 12-month partnership", "Deliverable: trainer toolkit and course materials"]}'::jsonb, 'book-open', '', 9)
on conflict (id) do nothing;
